---
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ infiniband_gpg_key }}"
    dest: /etc/apt/keyrings/infiniband.asc
    mode: '0644'

- name: Install GPG Key
  ansible.builtin.command: "gpg --dearmor -o /etc/apt/trusted.gpg.d/infiniband.gpg /etc/apt/keyrings/infiniband.asc"
  args:
    creates: /etc/apt/trusted.gpg.d/infiniband.gpg
  become: true

- name: Configure InfiniBand repository
  ansible.builtin.copy:
    content: "{{ infiniband_apt_repository }}\n"
    dest: /etc/apt/sources.list.d/infiniband.list
    mode: 0644

- name: Configure APT preferences for InfiniBand repository
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: {{ infiniband_apt_pin_release }}
      Pin-Priority: {{ infiniband_apt_priority }}
    dest: /etc/apt/preferences.d/priority-infiniband
    mode: 0644
  when: infiniband_apt_priority is defined

- name: "Update repository cache"
  apt:
    update_cache: yes
